import fs from "node:fs";
import path from "node:path";

import { compile, compileString } from "sass";

import {
  THEME_SELECTORS,
  selectorFor,
  type ThemeSelectorCandidateSource,
  type ThemeSelectorId,
  type ThemeSelectorStability,
} from "../src/theme-selectors";

const root = path.resolve(import.meta.dirname, "..");
const dist = path.join(root, "dist");
const themesOutput = path.join(dist, "themes");
const selectorScss = path.join(dist, "_theme-selectors.scss");
const selectorManifest = path.join(dist, "theme-selectors.json");

const stabilityRank: Record<ThemeSelectorStability, number> = {
  fallback: 0,
  structural: 1,
  semantic: 2,
  stable: 3,
  owned: 4,
};

const expectedSource: Partial<Record<ThemeSelectorCandidateSource, ThemeSelectorStability>> = {
  "klack-hook": "owned",
  "slack-generated": "fallback",
  "slack-structural": "structural",
};

const requiredSelectors = new Set<ThemeSelectorId>([
  "slack.app.root",
  "slack.channel-header.root",
  "slack.message.body",
  "slack.message.row",
]);

function validateRegistry(): void {
  const idPattern = /^(?:slack|klack)(?:\.[a-z][a-z0-9]*(?:-[a-z0-9]+)*){2,}$/;

  for (const required of requiredSelectors) {
    if (!THEME_SELECTORS[required]?.required) {
      throw new Error(`Required selector ${required} is absent or is not marked required`);
    }
  }

  for (const [id, definition] of Object.entries(THEME_SELECTORS)) {
    if (!idPattern.test(id)) throw new Error(`Invalid theme selector id: ${id}`);
    if (definition.candidates.length === 0) throw new Error(`Theme selector ${id} has no candidates`);

    const seen = new Set<string>();
    let previousRank = Number.POSITIVE_INFINITY;
    for (const candidate of definition.candidates) {
      const normalized = candidate.selector.trim();
      if (!normalized) throw new Error(`Theme selector ${id} has an empty candidate`);
      if (seen.has(normalized)) throw new Error(`Theme selector ${id} repeats ${normalized}`);
      seen.add(normalized);

      const expected = expectedSource[candidate.source];
      if (expected && candidate.stability !== expected) {
        throw new Error(`${id} marks ${candidate.source} as ${candidate.stability}; expected ${expected}`);
      }
      const rank = stabilityRank[candidate.stability];
      if (rank > previousRank) {
        throw new Error(`Theme selector ${id} puts ${candidate.stability} after a weaker candidate`);
      }
      previousRank = rank;

      try {
        compileString(`${candidate.selector} { --klack-selector-probe: 1; }`, {
          logger: { debug() {}, warn() {} },
        });
      } catch (error) {
        throw new Error(`Invalid CSS selector for ${id}: ${candidate.selector}`, { cause: error });
      }
    }

    const strongest = definition.candidates[0].stability;
    if (definition.required && (strongest === "structural" || strongest === "fallback")) {
      throw new Error(`Required theme selector ${id} only has fragile candidates`);
    }
  }
}

function sassString(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function generatedScss(): string {
  const entries = (Object.keys(THEME_SELECTORS) as ThemeSelectorId[])
    .map((id) => `  ${sassString(id)}: ${sassString(selectorFor(id))}`)
    .join(",\n");

  return `// Generated by scripts/build-themes.ts. Do not edit.\n@use "sass:map";\n@use "sass:string";\n\n$klack-theme-selectors: (\n${entries}\n);\n\n@function selector($id) {\n  @if not map.has-key($klack-theme-selectors, $id) {\n    @error "Unknown Klack theme selector: #{$id}";\n  }\n  @return string.unquote(map.get($klack-theme-selectors, $id));\n}\n`;
}

validateRegistry();
fs.mkdirSync(themesOutput, { recursive: true });
fs.writeFileSync(selectorScss, generatedScss());
fs.writeFileSync(selectorManifest, `${JSON.stringify(THEME_SELECTORS, null, 2)}\n`);

const minimalIrc = compile(path.join(root, "themes", "minimal-irc", "minimal-irc.theme.scss"), {
  loadPaths: [dist],
  logger: { debug() {}, warn() {} },
  style: "expanded",
});
fs.writeFileSync(path.join(themesOutput, "minimal-irc.theme.css"), minimalIrc.css);

console.log(`Built ${Object.keys(THEME_SELECTORS).length} theme selectors and 1 built-in theme`);
