export const KLACK_VERSION = "0.1.0";
export const BOOTSTRAP_PACKAGE_NAME = "klack-bootstrap";
export const ORIGINAL_ASAR_NAME = "_app.asar";
export const PLUGIN_CHANNEL = "KLACK_GET_PLUGINS";
export const PLUGIN_RELOAD_CHANNEL = "KLACK_RELOAD_PLUGINS";
export const THEME_RELOAD_CHANNEL = "KLACK_RELOAD_THEMES";
export const DIAGNOSTIC_CAPTURE_CHANNEL = "KLACK_CAPTURE_PAGE";
export const DIAGNOSTIC_COPY_CHANNEL = "KLACK_COPY_DIAGNOSTIC_REPORT";
